Feature/api token
Mirko-Solutions/basic-docker-symfony pull request #1
Opened 2022-10-19 14:49 UTC by AlexSokolianskiy-mirko

2022-10-19 15:09 UTC, konorws requested changes

2022-10-19 15:09 UTC, konorws commented on src/Application/Domain/Entity/User/UserToken.php
> +    public function setUser(?User $user): self
Токен не може бути без User тому не може приймати NULL

2022-10-19 15:09 UTC, konorws commented on src/Application/Domain/Entity/User/UserToken.php
> +    public function getUser(): ?User
методи які вертають Обєкт повині мати назви без get наприклад user()

2022-10-19 15:09 UTC, konorws commented on src/Application/Infrastructure/Repository/User/UserRepository.php
> +    private UserTokenRepository $userTokenRepository;
Додати відступ між методом та проперті

2022-10-19 15:09 UTC, konorws commented on src/Application/Infrastructure/Service/User/AuthService.php
> +    public function auth(array $data)
1. Потрібна більш коректна назва яка буде відповідати конкретній дії методу (наприклад createTokenHash і тому подіюне)
2. Метод повинен приймати або DTO або конкретні параметри так як валідація наявних в масиві елементів повина бути на стороні контролера а метод повинен приймати конкретні парметри Email та Пароль

2022-10-19 15:09 UTC, konorws commented on src/Application/Infrastructure/Service/User/AuthService.php
> +                $eml = new Email($userIdentifier);
Скорочувати так назви погана практика

2022-10-19 15:09 UTC, konorws commented on src/Application/Infrastructure/Service/User/AuthService.php
> +        $hash = hash('sha256', $token);
Використовувати метод Argon для шифрування

2022-10-19 15:09 UTC, konorws commented on src/Application/Infrastructure/Service/User/AuthService.php
> +        return $hash;
Лишня пуста лінія перед закритям методу + добавити пусту лінію перед ретурном

2022-10-19 15:09 UTC, konorws commented on src/Application/Infrastructure/Service/User/CreateTokenService.php
> +
Лишня пуста лінія

2022-10-19 15:09 UTC, konorws commented on src/Application/Security/ApiKeyAuthenticator.php
> +namespace App\Security;
Розмістити в розділі Infrastructure

2022-10-19 15:09 UTC, konorws commented on src/Application/Security/ApiKeyAuthenticator.php
> +        //TODO FIND BETTER WAY TO CHECK LOGIN ROUTE
Забрати такі коментарі

2022-10-19 15:09 UTC, konorws commented on src/Application/Security/ApiKeyAuthenticator.php
> +        if (str_starts_with($pathInfo, 'api/user/login')) {
Цей Роут винести в константу вище

2022-10-19 15:09 UTC, konorws commented on src/Application/Security/AuthenticationEntryPoint.php
> +namespace App\Security;
Розмістити в Infrastructure

2022-10-19 15:09 UTC, konorws commented on src/Application/UserInterface/API/Action/AbstractAction.php
> +            // dd($error->getMessage());
Закоментований код не потрібно пушити

2022-10-19 15:09 UTC, konorws commented on src/Application/UserInterface/API/Action/User/LoginAction.php
> +        return $this->response(new ArrayResponse(), ['token' => $token]);
Потрібно створити унікалтний респонс під Токен а не використовувати ArrayRespons як приклад і використовувати його лише для групування або графіків і тд

2022-10-19 15:09 UTC, konorws commented on src/config/packages/security.yaml
> -        - { path: ^/, roles: PUBLIC_ACCESS }
Чому ти це видалив ?

2022-10-20 06:46 UTC, AlexSokolianskiy-mirko commented on src/Application/Domain/Entity/User/UserToken.php
> +    public function getUser(): ?User
видалив, там трохи вище є вже такий метод

2022-10-20 06:48 UTC, AlexSokolianskiy-mirko commented on src/Application/Infrastructure/Repository/User/UserRepository.php
> +    private UserTokenRepository $userTokenRepository;
+

2022-10-20 08:24 UTC, AlexSokolianskiy-mirko commented on src/config/packages/security.yaml
> -        - { path: ^/, roles: PUBLIC_ACCESS }
я це додавав в процессі розробки і тільки потім розібрався як це працює, поняв що поки це не потрібно

2022-10-20 10:07 UTC, AlexSokolianskiy-mirko commented on src/Application/Domain/Entity/User/UserToken.php
> +    public function setUser(?User $user): self
виправив

2022-10-20 10:07 UTC, AlexSokolianskiy-mirko commented on src/Application/Infrastructure/Service/User/AuthService.php
> +    public function auth(array $data)
переписав

2022-10-20 10:08 UTC, AlexSokolianskiy-mirko commented on src/Application/Infrastructure/Service/User/AuthService.php
> +                $eml = new Email($userIdentifier);
виправив

2022-10-20 10:08 UTC, AlexSokolianskiy-mirko commented on src/Application/Security/ApiKeyAuthenticator.php
> +        if (str_starts_with($pathInfo, 'api/user/login')) {
виправив

2022-10-20 10:08 UTC, AlexSokolianskiy-mirko commented on src/Application/Security/AuthenticationEntryPoint.php
> +namespace App\Security;
переніс

2022-10-20 10:09 UTC, AlexSokolianskiy-mirko commented on src/Application/UserInterface/API/Action/AbstractAction.php
> +            // dd($error->getMessage());
зніс та додав тут вивод помилки при валідаціі

2022-10-20 10:09 UTC, AlexSokolianskiy-mirko commented on src/Application/UserInterface/API/Action/User/LoginAction.php
> +        return $this->response(new ArrayResponse(), ['token' => $token]);
зробив

2022-10-20 12:56 UTC, merged